name: Actualizar reporte UV

on:
  schedule:
    # Ejecutar cada 30 minutos
    - cron: "*/30 * * * *"

  # Permite ejecutar el proceso manualmente desde GitHub
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  uv:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependencias
        run: pip install requests

      - name: Consultar Meteochile y generar reporte
        env:
          DMC_USER: ${{ secrets.DMC_USER }}
          DMC_TOKEN: ${{ secrets.DMC_TOKEN }}
        run: python generate_uv.py

      - name: Guardar cambios
        run: |
          git config user.name "uv-bot"
          git config user.email "uv-bot@users.noreply.github.com"

          git add docs

          git diff --cached --quiet || git commit -m "Actualizar reporte UV"
          git push
